config/routes.rb
TwitterApp::Application.routes.draw do

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  

  resources :users
  resources :posts

  root 'posts#index'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  validates_uniqueness_of :login, :on => :update
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_confirmation_of :password
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post
    else
      render action: 'new'
    end

  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    if @post.save
      redirect_to @post
    else
      render action: 'edit'
    end
    
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html {
        redirect_to user_path(current_user)
      }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    # add custom create logic here
  end

  def update
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters
 
  protected
 
  # my custom fields are :name, :heard_how
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :heard_how,
        :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name,
        :email, :password, :password_confirmation, :current_password, :login)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def update
    # this didn't work.. created registrations controller to override devise
    @user.update_attributes(user_params)
    if @user.save
      redirect_to @user
    else
      render action: 'edit'
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TwitterApp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.top-bar
      %ul.title-area
        %li.name
          %h1=link_to "Twitter-Like App", root_path
        %li.toggle-topbar.menu-icon
          %span=link_to "Menu", "#"
      %section.top-bar-section
        %ul.right
          %li.divider
          - if user_signed_in?
            %li.active=link_to "My Account", user_path(current_user.id)
            %li.divider
            %li=link_to "Edit Profile", edit_user_registration_path
            %li.divider
            %li=link_to "Sign Out", destroy_user_session_path, method: :delete 
          - else
            %li=link_to "Sign Up", new_user_registration_path
            %li.divider
            %li=link_to "Sign In", new_user_session_path       


    / .row

    /   .large-11.large-centered.columns
    /     = link_to 'Home', root_url
    /     |
    /     - if user_signed_in?
    /       = link_to 'My Account', user_path(current_user.id)
    /       |
    /       = link_to 'Edit profile', edit_user_registration_path
    /       |
    /       = link_to "Sign out", destroy_user_session_path, method: :delete
    /     - else
    /       = link_to "Sign up", new_user_registration_path
    /       |
    /       = link_to "Sign in", new_user_session_path
    .row
      .large-8.large-centered.columns
      %p.notice= notice unless notice.blank?
      %p.alert= alert unless alert.blank?
      = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  - if @post.errors.any?
    %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
    %ul
      - @post.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.input :title
  .field
    = f.input :body
  .actions
    = f.submit 'Save'

app/views/posts/_index_post.html.haml
- @posts.reverse.each do |post|
  %h1= link_to post.title, post
  %p= post.updated_at.strftime("%A, %B %d, %Y at %l:%M%p") + " by #{post.user.email}"
  %p= post.body

app/views/posts/_show_post.html.haml
%h1= link_to @post.title, @post
%p= @post.updated_at.strftime("%A, %B %d, %Y at %l:%M%p") + " by #{@post.user.email}"
%p= @post.body
%p
    = link_to 'Edit', edit_post_path(@post)
    = link_to 'Delete', @post, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/edit.html.haml
%h1 Edit post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', user_path(current_user)

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/index.html.haml
= render 'index_post'

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/new.html.haml
%h1 Create a new post

= render 'form'
= link_to 'Back', user_path(current_user)

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/show.html.haml
=render 'show_post'

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.erb

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/show.html.haml
- if current_user.id == @user.id
  %ul
    %li= link_to "Post a Twitter-Like Post", new_post_path(@post)
- @user.posts.reverse.each do |post|
  %h2= link_to post.title, post
  %p
    = post.updated_at.strftime("%A, %B %d, %Y at %l:%M%p") 
    = "by #{post.user.email}" 

  %p= post.body
  %p
    = link_to 'Edit', edit_post_path(post)
    = link_to 'Delete', post, :method => :delete, :data => { :confirm => 'Are you sure?' }